"""Initial migration.

Revision ID: 083b2fd8fa96
Revises: 
Create Date: 2024-07-04 22:14:44.697205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083b2fd8fa96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
